app:
  sample_download_uri: "http://127.0.0.1:8091/uploads/samples"
  export_download_uri: "http://127.0.0.1:8091/uploads/exports"
  schedule_api: "http://school-schedule-container:8092"

kafka:
  brokers:
    - "kafka-kraft-container:9092"
  topic: "schedule_tasks"
  group_id: "schedule_engine_group"
