// Package tables
// This file is generated by GoAdmin CLI adm.
package tables

import (
	"github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"
	"gorm.io/gorm"
)

// Generators is a map of table models.
//
// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "schools" => http://localhost:9033/admin/info/schools
// "subjects" => http://localhost:9033/admin/info/subjects
// "semesters" => http://localhost:9033/admin/info/semesters
// "timeslots" => http://localhost:9033/admin/info/timeslots
// "teachers" => http://localhost:9033/admin/info/teachers
// "students" => http://localhost:9033/admin/info/students
// "classes" => http://localhost:9033/admin/info/classes
// "rooms" => http://localhost:9033/admin/info/rooms
// "requirements" => http://localhost:9033/admin/info/requirements
// "schedules" => http://localhost:9033/admin/info/schedules
//
// example end
var Generators = map[string]table.Generator{

	// "subjects":     GetSubjectsTable,
	"schools": GetSchoolsTable,
	// "semesters": GetSemestersTable,
	// "timeslots": GetTimeslotsTable,
	// "teachers":     GetTeachersTable,
	"students": GetStudentsTable,
	// "classes":      GetClassesTable,
	// "rooms":        GetRoomsTable,
	// "requirements": GetRequirementsTable,
	"schedules": GetSchedulesTable,

	// generators end
}

// GetGenerators collects tables that require dbConn
func GetGenerators(db *gorm.DB) table.GeneratorList {
	return table.GeneratorList{
		"bulkclasses":      GetBulkClassesTable(db),
		"bulkrequirements": GetBulkRequirementsTable(db),
		"bulksubjects":     GetBulkSubjectsTable(db),
		"bulktimeslots":    GetBulkTimeslotsTable(db),
		"bulkteachers":     GetBulkTeachersTable(db),

		"classes":      GetClassesTable(db),
		"rooms":        GetRoomsTable(db),
		"requirements": GetRequirementsTable(db),
		"semesters":    GetSemestersTable(db),
		"subjects":     GetSubjectsTable(db),
		"teachers":     GetTeachersTable(db),
		"timeslots":    GetTimeslotsTable(db),
		// Add more tables...
	}
}
