// This file is generated by GoAdmin CLI adm.
package tables

import (
	"github.com/GoAdminGroup/go-admin/modules/db"
	"github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"
)

// Generators is a map of table models.
//
// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "schools" => http://localhost:9033/admin/info/schools
// "subjects" => http://localhost:9033/admin/info/subjects
// "semesters" => http://localhost:9033/admin/info/semesters
// "timeslots" => http://localhost:9033/admin/info/timeslots
// "teachers" => http://localhost:9033/admin/info/teachers
// "students" => http://localhost:9033/admin/info/students
// "classes" => http://localhost:9033/admin/info/classes
// "rooms" => http://localhost:9033/admin/info/rooms
// "requirements" => http://localhost:9033/admin/info/requirements
// "schedules" => http://localhost:9033/admin/info/schedules
//
// example end
var Generators = map[string]table.Generator{

	"schools":      GetSchoolsTable,
	"subjects":     GetSubjectsTable,
	"semesters":    GetSemestersTable,
	"timeslots":    GetTimeslotsTable,
	"teachers":     GetTeachersTable,
	"students":     GetStudentsTable,
	"classes":      GetClassesTable,
	"rooms":        GetRoomsTable,
	"requirements": GetRequirementsTable,
	"schedules":    GetSchedulesTable,

	// generators end
}

// GetGenerators collects tables that require dbConn
func GetGenerators(dbConn db.Connection) table.GeneratorList {
	return table.GeneratorList{
		// "menu_items":       GetMenuitemsTable(dbConn),
		// Add more tables...
	}
}
